/**
 * Built-in bank templates.
 *
 * These are starting points measured from the physical stock, not artwork: they describe where
 * data lands on an already-printed cheque. Rule T6 — one template per stock design — is why NBE
 * ships as three entries (English personal, Arabic personal, A4 three-part voucher strip) rather
 * than one "Egyptian cheque" template.
 *
 * Every value here is a millimetre measurement an operator is expected to verify against their own
 * book with a ruler and then calibrate per printer; the designer's test page exists for that. The
 * `signature` and `micr` entries are deliberately `isPrinted: false`: the drawer signs by hand, and
 * this phase implements no MICR encoder.
 */

import { createBankChequeTemplate, createTemplateField } from './BankChequeTemplate'
import type { BankChequeTemplate, PreprintedFlags } from './types'

/** US/EU bank-stock width of 8.5in with the common 85mm height used across Egyptian print vendors. */
const STANDARD_STOCK = { widthMm: 210, heightMm: 85 } as const

/** A4 voucher sheet: three cheques stacked, and this template targets the middle one. */
const A4_VOUCHER_SHEET = { widthMm: 210, heightMm: 297 } as const
const VOUCHER_BODY = { bodyOriginMm: { xMm: 0, yMm: 106 }, bodyWidthMm: 210, bodyHeightMm: 85 } as const

const ALL_PREPRINTED: PreprintedFlags = {
  hasPayeeCaption: true,
  hasDateCaption: true,
  hasMemoCaption: true,
  hasAmountBox: true,
  hasDollarsCaption: true,
  hasSignatureCaption: true,
  hasRules: true,
  hasBankArtwork: true,
  hasSecurityBackground: true,
  hasMicrBand: true,
}

/**
 * Fixed, deliberate stamps. Built-ins are data, not "the moment the module was imported": a
 * timestamp that drifts on every load would make an idempotent save look like a change.
 */
const BUILTIN_STAMPED_AT = '2026-01-01T00:00:00.000Z'

const FONT_SERIF = 'Times New Roman'
const FONT_SANS = 'Helvetica'
const FONT_ARABIC = 'Traditional Arabic'

function englishPersonalFields() {
  return [
    createTemplateField({
      id: 'date',
      key: 'date',
      label: 'Date',
      role: 'value',
      xMm: 152,
      yMm: 16,
      widthMm: 46,
      heightMm: 7,
      fontFamily: FONT_SERIF,
      fontSizePt: 11,
      format: 'date-DDMMYYYY',
      alignment: { horizontal: 'right', vertical: 'middle' },
      overflow: 'clip',
      zIndex: 2,
    }),
    createTemplateField({
      id: 'cheque-number-top',
      key: 'chequeNumber',
      label: 'Cheque number',
      xMm: 182,
      yMm: 6,
      widthMm: 22,
      heightMm: 5.5,
      fontFamily: FONT_SANS,
      fontSizePt: 8,
      format: 'text',
      alignment: { horizontal: 'right', vertical: 'top' },
      overflow: 'clip',
      zIndex: 2,
    }),
    createTemplateField({
      id: 'payee',
      key: 'payee',
      label: 'Pay to the order of',
      xMm: 26,
      yMm: 33.5,
      widthMm: 118,
      heightMm: 8,
      fontFamily: FONT_SERIF,
      fontSizePt: 12,
      alignment: { horizontal: 'left', vertical: 'middle' },
      overflow: 'shrink',
      maxChars: 55,
      required: true,
      zIndex: 3,
    }),
    createTemplateField({
      id: 'amount-numeric',
      key: 'amountNumeric',
      label: 'Amount (figures)',
      xMm: 148,
      yMm: 33.5,
      widthMm: 50,
      heightMm: 8,
      fontFamily: FONT_SERIF,
      fontSizePt: 11,
      fontWeight: 700,
      format: 'amount-2dp',
      alignment: { horizontal: 'right', vertical: 'middle' },
      overflow: 'error',
      required: true,
      zIndex: 3,
    }),
    createTemplateField({
      id: 'amount-words',
      key: 'amountWords',
      label: 'Amount (words)',
      xMm: 26,
      yMm: 45,
      widthMm: 128,
      heightMm: 7.5,
      fontFamily: FONT_SERIF,
      fontSizePt: 9.5,
      format: 'amount-words-en',
      textTransform: 'uppercase',
      alignment: { horizontal: 'left', vertical: 'middle' },
      overflow: 'shrink',
      required: true,
      zIndex: 3,
    }),
    createTemplateField({
      id: 'memo',
      key: 'memo',
      label: 'Memo',
      xMm: 24,
      yMm: 68,
      widthMm: 74,
      heightMm: 6.5,
      fontFamily: FONT_SANS,
      fontSizePt: 8,
      alignment: { horizontal: 'left', vertical: 'middle' },
      overflow: 'clip',
      maxChars: 48,
      zIndex: 1,
    }),
    // Preview-only guides: the drawer signs on the paper, and the MICR band is not this app's job.
    createTemplateField({
      id: 'signature-guide',
      key: 'signature',
      label: 'Signature area (hand-signed)',
      role: 'guide',
      xMm: 150,
      yMm: 66,
      widthMm: 48,
      heightMm: 9,
      fontSizePt: 7,
      alignment: { horizontal: 'center', vertical: 'bottom' },
      overflow: 'clip',
      isPrinted: false,
      zIndex: 0,
    }),
    createTemplateField({
      id: 'micr-guide',
      key: 'micr',
      label: 'MICR band (pre-printed by the bank)',
      role: 'guide',
      xMm: 12,
      yMm: 73,
      widthMm: 170,
      heightMm: 9,
      fontFamily: 'MICR Encode',
      fontSizePt: 9,
      isMicr: true,
      alignment: { horizontal: 'left', vertical: 'middle' },
      overflow: 'clip',
      isPrinted: false,
      zIndex: 0,
    }),
  ]
}

function arabicPersonalFields() {
  return [
    createTemplateField({
      id: 'date',
      key: 'date',
      label: 'التاريخ',
      xMm: 148,
      yMm: 15,
      widthMm: 48,
      heightMm: 7,
      fontFamily: FONT_ARABIC,
      fontSizePt: 12,
      format: 'date-DDMMYYYY',
      direction: 'rtl',
      alignment: { horizontal: 'left', vertical: 'middle' },
      overflow: 'clip',
      zIndex: 2,
    }),
    createTemplateField({
      id: 'cheque-number-top',
      key: 'chequeNumber',
      label: 'رقم الشيك',
      xMm: 12,
      yMm: 6,
      widthMm: 24,
      heightMm: 5.5,
      fontFamily: FONT_SANS,
      fontSizePt: 8,
      direction: 'ltr',
      alignment: { horizontal: 'left', vertical: 'top' },
      overflow: 'clip',
      zIndex: 2,
    }),
    createTemplateField({
      id: 'payee',
      key: 'payee',
      label: 'ادفعوا لأمر',
      xMm: 60,
      yMm: 32,
      widthMm: 128,
      heightMm: 9,
      fontFamily: FONT_ARABIC,
      fontSizePt: 14,
      direction: 'auto',
      alignment: { horizontal: 'right', vertical: 'middle' },
      overflow: 'shrink',
      maxChars: 42,
      required: true,
      zIndex: 3,
    }),
    createTemplateField({
      id: 'amount-words',
      key: 'amountWords',
      label: 'فقط',
      xMm: 56,
      yMm: 45,
      widthMm: 132,
      heightMm: 8,
      fontFamily: FONT_ARABIC,
      fontSizePt: 11,
      format: 'amount-words-ar',
      direction: 'rtl',
      alignment: { horizontal: 'right', vertical: 'middle' },
      overflow: 'shrink',
      required: true,
      zIndex: 3,
    }),
    createTemplateField({
      id: 'amount-numeric',
      key: 'amountNumeric',
      label: 'المبلغ',
      xMm: 14,
      yMm: 44,
      widthMm: 40,
      heightMm: 9,
      fontFamily: FONT_SERIF,
      fontSizePt: 11,
      fontWeight: 700,
      format: 'amount-2dp',
      direction: 'ltr',
      alignment: { horizontal: 'right', vertical: 'middle' },
      overflow: 'error',
      required: true,
      zIndex: 3,
    }),
    createTemplateField({
      id: 'memo',
      key: 'memo',
      label: 'البيان',
      xMm: 118,
      yMm: 67,
      widthMm: 76,
      heightMm: 7,
      fontFamily: FONT_ARABIC,
      fontSizePt: 10,
      direction: 'rtl',
      alignment: { horizontal: 'right', vertical: 'middle' },
      overflow: 'clip',
      maxChars: 40,
      zIndex: 1,
    }),
    createTemplateField({
      id: 'account-number',
      key: 'accountNumber',
      label: 'رقم الحساب',
      xMm: 12,
      yMm: 67,
      widthMm: 60,
      heightMm: 6.5,
      fontFamily: FONT_SANS,
      fontSizePt: 8,
      direction: 'ltr',
      alignment: { horizontal: 'left', vertical: 'middle' },
      overflow: 'clip',
      zIndex: 1,
    }),
    createTemplateField({
      id: 'micr-guide',
      key: 'micr',
      label: 'شريط MICR (مطبوع مسبقاً)',
      role: 'guide',
      xMm: 12,
      yMm: 73,
      widthMm: 170,
      heightMm: 9,
      fontFamily: 'MICR Encode',
      fontSizePt: 9,
      isMicr: true,
      alignment: { horizontal: 'left', vertical: 'middle' },
      overflow: 'clip',
      isPrinted: false,
      zIndex: 0,
    }),
  ]
}

const NBE_ENGLISH = createBankChequeTemplate({
  id: 'nbe-personal-en-2024',
  bankId: 'bank:nbe',
  bankName: 'National Bank of Egypt',
  name: 'NBE — Personal Cheque — English 2024 stock',
  stockType: 'personal-en',
  stockReference: 'NBE-PERS-EN-85',
  description:
    'Standard NBE personal cheque, English captions, pre-printed payee/date/memo rules, amount box and MICR band.',
  paper: { ...STANDARD_STOCK, orientation: 'landscape', bodyOriginMm: { xMm: 0, yMm: 0 }, bodyWidthMm: 210, bodyHeightMm: 85 },
  fields: englishPersonalFields(),
  preprinted: ALL_PREPRINTED,
  defaultDirection: 'ltr',
  defaultLocale: 'en-EG',
  printerConfigHint: { paperFeed: 'manual', duplex: 'none', colourMode: 'mono' },
  createdAt: BUILTIN_STAMPED_AT,
  updatedAt: BUILTIN_STAMPED_AT,
})

const NBE_ARABIC = createBankChequeTemplate({
  id: 'nbe-personal-ar-2024',
  bankId: 'bank:nbe',
  bankName: 'National Bank of Egypt',
  name: 'NBE — Personal Cheque — Arabic 2024 stock',
  stockType: 'personal-ar',
  stockReference: 'NBE-PERS-AR-85',
  description: 'RTL Arabic personal cheque. Payee and words lines are RTL; figures and account numbers stay LTR.',
  paper: { ...STANDARD_STOCK, orientation: 'landscape', bodyOriginMm: { xMm: 0, yMm: 0 }, bodyWidthMm: 210, bodyHeightMm: 85 },
  fields: arabicPersonalFields(),
  preprinted: ALL_PREPRINTED,
  defaultDirection: 'rtl',
  defaultLocale: 'ar-EG',
  printerConfigHint: { paperFeed: 'manual', duplex: 'none', colourMode: 'mono' },
  createdAt: BUILTIN_STAMPED_AT,
  updatedAt: BUILTIN_STAMPED_AT,
})

const NBE_VOUCHER_A4 = createBankChequeTemplate({
  id: 'nbe-voucher-a4-3part',
  bankId: 'bank:nbe',
  bankName: 'National Bank of Egypt',
  name: 'NBE — A4 Voucher Sheet — middle cheque of 3',
  stockType: 'voucher-a4',
  stockReference: 'NBE-VCHR-A4-3',
  description:
    'Three cheques per A4 sheet with the counterfoil below; the body is the middle band, so every field is offset by the sheet, not by the cheque.',
  paper: { ...A4_VOUCHER_SHEET, orientation: 'portrait', ...VOUCHER_BODY },
  // Deliberately the *same* field table as the standalone stock: field geometry is body-relative,
  // and bodyOriginMm is what moves the whole layout down to the middle cheque of the sheet.
  fields: englishPersonalFields(),
  preprinted: { ...ALL_PREPRINTED, hasSecurityBackground: false },
  defaultDirection: 'ltr',
  defaultLocale: 'en-EG',
  printerConfigHint: { paperFeed: 'tray', trayId: '1', duplex: 'none', colourMode: 'mono' },
  createdAt: BUILTIN_STAMPED_AT,
  updatedAt: BUILTIN_STAMPED_AT,
})

const CIB_ENGLISH = createBankChequeTemplate({
  id: 'cib-corporate-en-2023',
  bankId: 'bank:cib',
  bankName: 'Commercial International Bank',
  name: 'CIB — Corporate Cheque — English',
  stockType: 'corporate-en',
  stockReference: 'CIB-CORP-EN-190',
  description: 'Narrower 190mm corporate stock: drawer block is printed by the app, date and words share a line.',
  paper: { widthMm: 190, heightMm: 80, orientation: 'landscape', bodyOriginMm: { xMm: 0, yMm: 0 }, bodyWidthMm: 190, bodyHeightMm: 80 },
  fields: [
    createTemplateField({
      id: 'drawer',
      key: 'drawer',
      label: 'Drawer block',
      xMm: 8,
      yMm: 6,
      widthMm: 74,
      heightMm: 11,
      fontFamily: FONT_SANS,
      fontSizePt: 7.5,
      source: 'drawerName',
      overflow: 'wrap',
      alignment: { horizontal: 'left', vertical: 'top' },
      zIndex: 1,
    }),
    createTemplateField({
      id: 'bank-info',
      key: 'bankInfo',
      label: 'Bank',
      xMm: 8,
      yMm: 18,
      widthMm: 74,
      heightMm: 5.5,
      fontFamily: FONT_SANS,
      fontSizePt: 6.5,
      source: 'bankName',
      overflow: 'clip',
      alignment: { horizontal: 'left', vertical: 'top' },
      zIndex: 1,
    }),
    createTemplateField({
      id: 'date',
      key: 'date',
      label: 'Date',
      xMm: 132,
      yMm: 8,
      widthMm: 50,
      heightMm: 7,
      fontFamily: FONT_SERIF,
      fontSizePt: 10,
      format: 'date-DDMMYYYY',
      alignment: { horizontal: 'right', vertical: 'middle' },
      overflow: 'clip',
      zIndex: 2,
    }),
    createTemplateField({
      id: 'payee',
      key: 'payee',
      label: 'Pay to',
      xMm: 22,
      yMm: 32,
      widthMm: 104,
      heightMm: 8,
      fontFamily: FONT_SERIF,
      fontSizePt: 11,
      overflow: 'shrink',
      maxChars: 48,
      required: true,
      zIndex: 3,
    }),
    createTemplateField({
      id: 'amount-numeric',
      key: 'amountNumeric',
      label: 'Amount',
      xMm: 130,
      yMm: 31,
      widthMm: 52,
      heightMm: 9,
      fontFamily: FONT_SERIF,
      fontSizePt: 11,
      fontWeight: 700,
      format: 'amount-2dp',
      alignment: { horizontal: 'right', vertical: 'middle' },
      overflow: 'error',
      required: true,
      zIndex: 3,
    }),
    createTemplateField({
      id: 'amount-words',
      key: 'amountWords',
      label: 'Words',
      xMm: 22,
      yMm: 44,
      widthMm: 104,
      heightMm: 7.5,
      fontFamily: FONT_SERIF,
      fontSizePt: 9,
      format: 'amount-words-en',
      overflow: 'shrink',
      required: true,
      zIndex: 3,
    }),
    createTemplateField({
      id: 'cheque-number',
      key: 'chequeNumber',
      label: 'Cheque number',
      xMm: 132,
      yMm: 68,
      widthMm: 50,
      heightMm: 6.5,
      fontFamily: FONT_SANS,
      fontSizePt: 8,
      format: 'number-padded',
      alignment: { horizontal: 'right', vertical: 'middle' },
      overflow: 'clip',
      zIndex: 2,
    }),
    createTemplateField({
      id: 'branch-code',
      key: 'branch-code',
      label: 'Branch code',
      source: 'custom',
      customKey: 'branchCode',
      xMm: 8,
      yMm: 68,
      widthMm: 44,
      heightMm: 6,
      fontFamily: FONT_SANS,
      fontSizePt: 7,
      direction: 'ltr',
      alignment: { horizontal: 'left', vertical: 'middle' },
      overflow: 'clip',
      zIndex: 1,
    }),
  ],
  preprinted: { ...ALL_PREPRINTED, hasPayeeCaption: true, hasRules: true },
  defaultDirection: 'ltr',
  defaultLocale: 'en-EG',
  printerConfigHint: { paperFeed: 'sheet', duplex: 'none' },
  createdAt: BUILTIN_STAMPED_AT,
  updatedAt: BUILTIN_STAMPED_AT,
})

export const BUILTIN_TEMPLATES: readonly BankChequeTemplate[] = [
  NBE_ENGLISH,
  NBE_ARABIC,
  NBE_VOUCHER_A4,
  CIB_ENGLISH,
]

export const BUILTIN_TEMPLATE_IDS = BUILTIN_TEMPLATES.map((template) => template.id)

export function builtinTemplateById(id: string): BankChequeTemplate | undefined {
  return BUILTIN_TEMPLATES.find((template) => template.id === id)
}
